In [1]:
import torch
torch.__version__

'2.5.1+cpu'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
# Check the number of dimensions of vector
vector.ndim

1

In [13]:
# Check shape of vector
vector.shape

torch.Size([2])

In [14]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
# Check number of dimensions
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [20]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])